openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0

paths:
  /api/auth/signup:
    post:
      summary: Sign up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                email: { type: string }
                password: { type: string }
      responses:
        201:
          description: Created

  /api/products:
    get:
      summary: List products
      responses:
        200:
          description: OK
